//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App3
{
    using System;
    using System.Collections.Generic;

    public class Car
    {
         public Car()
        {
            this.Missions = new HashSet<Mission>();
        }
    
        public int id_Car { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public virtual ICollection<Mission> Missions { get; set; }
    }
}
