//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App3
{
    using System;
    using System.Collections.Generic;
    
   public class Mission
    {
         public Mission()
        {
            this.Geolocalisations = new HashSet<Geolocalisation>();
            this.Reports = new HashSet<Report>();
        }
    
        public Nullable<System.DateTime> Datetime_Departure { get; set; }
        public Nullable<System.DateTime> Datetime_Arrival { get; set; }
        public int id_mission { get; set; }
        public int id_driver { get; set; }
        public int id_Car { get; set; }
        public string name_mission { get; set; }

        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
         public virtual ICollection<Geolocalisation> Geolocalisations { get; set; }
         public virtual ICollection<Report> Reports { get; set; }
    }
}
