//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App3
{
    using System;
    using System.Collections.Generic;

    public class Report
    {
        public int id_report { get; set; }
        public Nullable<int> id_mission { get; set; }
        public string commentary_problem { get; set; }
        public string name_rapport { get; set; }
        public virtual Mission Mission { get; set; }
    }
}
